# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20170812_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_age',
            field=models.FloatField(),
        ),
    ]
