# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170812_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_verified_mobile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='my_age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='my_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='Null', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Null', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='Null', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Null', max_length=120),
        ),
    ]
