# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170813_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='Null', max_length=254),
        ),
    ]
